### ISSUE TITLE
for문 범위가 

### ISSUE THREAD

**Issue by potados99** [INU-Fake-Developers/IamJunYoung#2]
![](https://static.wikia.nocookie.net/pokemon/images/5/57/이상해씨_공식_일러스트.png/revision/latest/scale-to-width-down/1000?cb=20170404232618&path-prefix=ko)

이상해씨

https://github.com/INU-Fake-Developers/IamJunYoung/blob/a8ba9e7cce258ee8b44903eb962607386e09c693/BOJ/10989.py#L9

**Comment by HamBP** [comment]
수정해씨
